//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkExamples
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductID { get; set; }
        public string Model { get; set; }
        public string PCBID { get; set; }
        public string PCBModel { get; set; }
        public string MAC { get; set; }
        public string UUID { get; set; }
        public string MBECR { get; set; }
        public string CVSN { get; set; }
        public string CUSTSN { get; set; }
        public string ECR { get; set; }
        public string PizzaID { get; set; }
        public string MO { get; set; }
        public Nullable<decimal> UnitWeight { get; set; }
        public string CartonSN { get; set; }
        public Nullable<decimal> CartonWeight { get; set; }
        public string DeliveryNo { get; set; }
        public string PalletNo { get; set; }
        public string State { get; set; }
        public string OOAID { get; set; }
        public string PRSN { get; set; }
        public System.DateTime Cdt { get; set; }
        public System.DateTime Udt { get; set; }
    }
}
